
# Magic numbers
USERNAME_MAX_LENGTH = 150
EMAIL_MAX_LENGTH = 254
ROLE_MAX_LENGTH = 10
BIO_MAX_LENGTH = 250
CONFIRMATION_CODE_MAX_LENGTH = 500
YEAR_MAX_LENGTH = 4
CATEGORY_NAME = 256
CATEGORY_SLUG = 50
GENRE_NAME = 256
GENRE_SLUG = 50
TITLE_NAME = 256
MIN_USERNAME_LENGTH = 2
FORBIDDEN_USERNAMES = ['me', ]
SCORE_MIN_VALUE_VALIDATOR = 0
SCORE_MAX_VALUE_VALIDATOR = 10
TEXT_SYMBOL_SLICE = 20
