# Generated by Django 3.2 on 2024-08-30 21:08

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20240830_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(db_index=True, validators=[reviews.models.validate_year], verbose_name='Год'),
        ),
    ]
