# Generated by Django 3.2 on 2024-09-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20240831_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(default='No description provided', verbose_name='Описание'),
        ),
    ]
